# Some general musing on publishing papers for those about to try it out {#Ferry}

**Lara Ferry**


*School of Mathematical and Natural Sciences,Arizona State University, Phoenix, Arizona.*


**RUN!**  Just kidding. It actually is really quite rewarding to see your work in print (virtual as that may be these days).  And, I do encourage it early, and often, for my own undergraduate and graduate students.  But, I do feel like I need to put a little safety bubble around them when they are first starting out.
 

Bear in mind that I, myself, have never had a paper published by a journal without receiving a request for fairly major revisions, to this date. So, I write this article from the perspective of serving on the editorial boards now of several journals, and serving presently as the Senior Executive Editor of the journal *Functional Ecology*.  I am officially ‘old’, in academic terms. But, some of the scars from my early years as a developing author still feel as fresh as the day they arrived (yes, I have been around long enough that my first few manuscripts were printed and sent via snail mail, in an envelope!). So, I write this piece now thinking of my own experience as an author, and I reiterate that, even with these editorial positions under my belt, I still get reviews that ask for quite major revisions from me, nearly every time.  It happens to us all, and it is a reflection of the process. We don’t outgrow this kind of feedback, we just get thicker skins. 

## Focussing on the ‘why’.

The process is pretty trimmed down, especially these days. Only a couple of people read your paper – two, maybe three reviewers, maybe an associate editor, an editor – and they are doing their best to make sure that only really good work gets into the journal. And, that is a good thing.  No one wants to read junk. And, journals have to survive, and to survive, they need readers. The singular and imperfect measure of this is [Impact Factors](http://www.howtopublishscience.org/impactfactor.html), and the like, but that is a rant for another day.

You should view the really critical comments on your paper as the generous gift that they are. Painful, possibly, yes. But, writing those kinds of reviews is incredibly time consuming.  And, typically, a review is something that faculty member X had to do at home, at night, as it couldn’t be fit into the regular work day of teaching, researching, serving, etc. So, read the review, set it aside, and then come back to it when the feelings have subsided a little and re-read it as the supportive document that it was meant to be. Someone, probably someone you don’t even know, has taken time to try improve your work sufficiently for it to be published in a journal. Make the changes (don’t argue with this person who has given you this gift). If the reviewer misunderstood what you, the author, meant, rewrite it. That is on you, not the reviewer. And, so on.

## Sometimes it gets personal

Of course, we have all seen the reviews where it got personal. The reviewer felt compelled to fix something, probably not you, the author, and was going to do it through the review.  So, they are really over critical. These are actually really rare. Yes, these folks exist. Good editors learn about them and weed them out of the system. If you think you got an unfair review from one of these kinds of people, and it didn’t get addressed by the editor, reach out. Let the editor know your thoughts. Politely, please, editors are people too.  But, editors are here to help you through the process, and to help young writers learn their craft.

Bear in mind too that this profession we are in, which requires academic publishing, and perhaps all of academia, if you are in that line of work, is based, exclusively, on negative feedback. We cut our teeth as young scientists, in graduate school, in the ‘Journal Club’ or some group meeting with the universal and singular goal to ‘review important papers in the field’. Review, in nearly every case, equates to shred. Never mind that the paper was published in Science or Nature or another of those quite exceptional top-tier publications. And, pay no attention to the fact that every student in the room has some publications under their belt that is less than 1.  We are trained, like lion cubs, to go for the kill. This means that the fact that you only got negative feedback on your manuscript, and that it feels picked over like buzzards were at a road kill, isn’t personal, and is merely the current culture of academia. I am not saying this culture is good, or defending it in any way. I am just saying that is how it is, at least at present. I hope for a day when this isn’t the case any longer, and I do see the culture shifting to one that is much more supportive of young authors (this book is a case in point). But, we have a ways to go still.

## You'll need a support system

So, build your support system, and rely on it in as you develop your writing prowess. Know that you will continue to need them, and think of them as a lifelong network. I am reminded of a recent paper with a collaborator whom I have worked with every now and then since we were in graduate school together. The paper was rejected from *Science*, but then a writer from *Science* reached out when it was published in a different journal, and the publication was subsequently featured as a highlight. Go figure. You never know where the road is going to take you when you embark upon it.  But, take the journey, and be open to its twists and turns. 
